### ISSUE TITLE
Supporting private members

### ISSUE THREAD

**Issue by stefan-hausmann** [uhop/dcl#10]
Would it be possible to add private member support to the library, i.e.

```
var myType = dcl(
    null,
    {
        constructor: function()
        {
            //some way to access private members, e.g. via closure or this.private or something...          
        },

        publicFunction: function()
        {
            //some way to access private members, e.g. via closure or this.private or something...          

            return 'abc';
        },

        publicVariable: 'abc',

        private:
        {
            privateFunction: function()
            {
                return 'xzy'
            }

            privateVariable: 'xyz'
        }   
    }
);

myInstance = new myType();

console.log(myInstance.publicFunction());
--> abc

console.log(myInstance.publicVariable);
--> abc

console.log(myInstance.privateFunction());
--> undefined

console.log(myInstance.privateVariable);
--> undefined
```

or would there be any problems implementing such an extension with the current library's architecture?

If so, how would you recommend dealing with encapsulating private members so that they cannot be accessed from outside? I know JavaScript doesn't support the concept of private members natively, but given that your library already adds a lot of object oriented fashion, I would find it very useful to have the ability to more "encapsulate" things in larger projects....

Best regards,
Stefan

**Comment by uhop** [comment]
It looks like ECMAScript is going to have private members: https://github.com/tc39/proposal-class-fields

Let's plan to use those rather than reinvent the wheel.

But, if there are proved to be insufficient, or never make it to the standard, we'll revisit this ticket.
