### ISSUE TITLE
instanceOf ?

### ISSUE THREAD

**Issue by mc007** [uhop/dcl#19]
Hi,
what is the instanceOf equivalent in dcl? I'd like to compare 2 module instances by class I just don't know how. 
Thank you!
g

**Comment by uhop** [comment]
There are two ways to do it:

1. Use `instanceof` for linear inheritance. It works for all base classes. (`dcl` produces normal JavaScript inheritance compatible with everything).

2. Use [`dcl.isInstanceOf()`](http://www.dcljs.org/docs/dcl_js/isinstanceof/). It works for mixins and bases alike. Besides the documentation, you can look at [tests of `dcl.isInstaceOf()`](https://github.com/uhop/dcl/blob/master/tests/test_dcl.js#L137).

**Comment by mc007** [comment]
yeah, just came to the same after all.
thanks for the heads up!
g
