### ISSUE TITLE
webpack warning when importing dcl / dynamic use of require calls

### ISSUE THREAD

**Issue by stefan-hausmann** [uhop/dcl#24]
First of all, thanks @uhop for your new major release - it's great that you're continuosly improving the library!

When using it on a node.js project with webpack bundling, webpack gives the following warnings:
```
WARNING in ./node_modules/dcl/dcl.js
1:94-101 Critical dependency: require function is used in a way in which dependencies cannot be statically extracted

WARNING in ./node_modules/dcl/dcl.js
1:162-172 Critical dependency: the request of a dependency is an expression
```
seems it cannot do a static analysis on required modules because of the
```
/* UMD.define */ (typeof define=="function"&&define||function(d,f,m){m={module:module,require:require};module.exports=f.apply(null,d.map(function(n){return m[n]||require(n)}))})
```
line where a variable is passed to the require function.

For more information, also please have a look at the discussion in https://github.com/webpack/webpack/issues/196.

Could this be easily replaced with more static parameters to the require function?

Thanks & with best regards,
Stefan

**Comment by uhop** [comment]
I already build a version with globals for browsers (some people prefer this style as being easier to integrate). It looks like I should start build a special static version for tools like `webpack`.

**Comment by clubajax** [comment]
@uhop: Depending on if you are using web components or not, webpack could use the source (if using WC, it needs to be babel-ized). It could be a simple matter of changing the "main" in the npm package.

**Comment by uhop** [comment]
I looked into that more. For browser + Babel, it is easier to use `dcl` with globals (see `dist` directory). For node + Babel, it works out of box as is (Babel can import CommonJS modules without problems without compiling them). Just don't compile `dcl`.

**Comment by uhop** [comment]
I added ES6 distro in dd2fceb04a04d381eff74ecca21b90cc70f02679. How to use it documented in README. Try it, and reopen the ticket, if you have any problems. I am interested to play nice with Babel in all possible configurations, because ES6 will be a native version of the upcoming `dcl6`.

**Comment by uhop** [comment]
I tried it in the real React project. Use 2.0.5, which has some downgraded prologue for ES6 modules. The original 2.0.3 has used a lambda, which was some reason was rejected by Babel.
