### ISSUE TITLE
dcl v2 spurious cycle errors

### ISSUE THREAD

**Issue by wkeese** [uhop/dcl#27]
I'm getting "cycle" errors from DCL V2 for code that worked in DCL V1 and seems like it should work in DCL V2 (i.e. I think the C3MRO algorithm should be able to handle it).  For example:

```
var Base1 = dcl({});
var Base2 = dcl({});
var Base1Extended = dcl(Base1, {})
var Button = dcl([Base2, Base1Extended], {});
dcl([Button, Base1], {});
```

Or, am I misunderstanding the requirements?  (I would expect this to be flattened to Button --> Base2 --> Base1Extended --> Base1.)

**Comment by uhop** [comment]
Interesting that I fixed this bug in `dcl6` quite a long time ago, but was under impression that I backported it. Apparently, I was wrong. Now they should be in sync.
