### ISSUE TITLE
Wrong amount of arguments

### ISSUE THREAD

**Issue by clubajax** [uhop/dcl#3]
When I try to make a simple class:

``` javascript
dcl({constructor:function(){}});
```

I get a very cryptic error, "Uncaught TypeError: Cannot read property 'constructor' of undefined"

One of two things would help here: handle that use case (my preferred), or do a check for the correct arguments to throw a warning and log the object so it's easier to find the offender. I did this on line 19 in mini.js:

``` javascript
if(typeof superClass === 'object' && !props){
    var disp = superClass && superClass.declaredClass ? superClass.declaredClass : superClass;
    var msg = 'Wrong amount of arguments used for DCL';
    console.error(msg, superClass);
    throw new Error(msg);
}
```

**Comment by uhop** [comment]
Addressed in 2.0.
