### ISSUE TITLE
can't override DOM element native properties on IE, FF

### ISSUE THREAD

**Issue by wkeese** [uhop/dcl#9]
IE is touchy about properties in DOM classes; in particular this doesn't work:

> dcl(HTMLInputElement, {name: ""})

It throws an error:

> Invalid Calling Object.

I can get the same error with a non-dcl test case as:

> d = Object.create("HTMLInputElement")
> d.name = 123;

and also simply accessing that name field:

> HTMLInputElement.prototype.name

However this (below) does work:

> d = Object.create("HTMLInputElement")
> Object.defineProperty(d, "name", { value: 123 });

I don't know if we should consider this as a bug or as a limitation.

If it's a bug then the solution is probably to use `Object.defineProperties()` rather than `dcl.mix()` to mix in the properties to the new class.

What do you think?

**Comment by uhop** [comment]
Addressed in 2.0.
